<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-1EHUG3JI" failures="1" tests="3" name="com.selenium.framework.tests.testingTESTxmlFile2" time="35.206" errors="0" timestamp="2021-10-12T04:00:29 EDT" skipped="1">
  <testcase classname="com.selenium.framework.tests.testingTESTxmlFile2" name="setUp" time="22.947">
    <failure message="expected [My Store] but found [Login - My Store]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [My Store] but found [Login - My Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.selenium.framework.libraries.seleniumBase.setUp(seleniumBase.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase classname="com.selenium.framework.tests.testingTESTxmlFile2" name="testCreatingAccountUsingSameEmail22" time="0.000">
    <skipped/>
  </testcase> <!-- testCreatingAccountUsingSameEmail22 -->
  <system-out/>
  <testcase classname="com.selenium.framework.tests.testingTESTxmlFile2" name="testSignInRightCredentials22" time="12.259"/>
  <system-out/>
</testsuite> <!-- com.selenium.framework.tests.testingTESTxmlFile2 -->
